# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stats.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstats.proto\x12\x15\x65xperimental.v2rayapi\".\n\x0fGetStatsRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05reset\x18\x02 \x01(\x08\"#\n\x04Stat\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x03\"=\n\x10GetStatsResponse\x12)\n\x04stat\x18\x01 \x01(\x0b\x32\x1b.experimental.v2rayapi.Stat\"U\n\x11QueryStatsRequest\x12\x0f\n\x07pattern\x18\x01 \x01(\t\x12\r\n\x05reset\x18\x02 \x01(\x08\x12\x10\n\x08patterns\x18\x03 \x03(\t\x12\x0e\n\x06regexp\x18\x04 \x01(\x08\"?\n\x12QueryStatsResponse\x12)\n\x04stat\x18\x01 \x03(\x0b\x32\x1b.experimental.v2rayapi.Stat\"\x11\n\x0fSysStatsRequest\"\xc2\x01\n\x10SysStatsResponse\x12\x14\n\x0cNumGoroutine\x18\x01 \x01(\r\x12\r\n\x05NumGC\x18\x02 \x01(\r\x12\r\n\x05\x41lloc\x18\x03 \x01(\x04\x12\x12\n\nTotalAlloc\x18\x04 \x01(\x04\x12\x0b\n\x03Sys\x18\x05 \x01(\x04\x12\x0f\n\x07Mallocs\x18\x06 \x01(\x04\x12\r\n\x05\x46rees\x18\x07 \x01(\x04\x12\x13\n\x0bLiveObjects\x18\x08 \x01(\x04\x12\x14\n\x0cPauseTotalNs\x18\t \x01(\x04\x12\x0e\n\x06Uptime\x18\n \x01(\r2\xb4\x02\n\x0cStatsService\x12]\n\x08GetStats\x12&.experimental.v2rayapi.GetStatsRequest\x1a\'.experimental.v2rayapi.GetStatsResponse\"\x00\x12\x63\n\nQueryStats\x12(.experimental.v2rayapi.QueryStatsRequest\x1a).experimental.v2rayapi.QueryStatsResponse\"\x00\x12`\n\x0bGetSysStats\x12&.experimental.v2rayapi.SysStatsRequest\x1a\'.experimental.v2rayapi.SysStatsResponse\"\x00\x42\x34Z2github.com/sagernet/sing-box/experimental/v2rayapib\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stats_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z2github.com/sagernet/sing-box/experimental/v2rayapi'
  _GETSTATSREQUEST._serialized_start=38
  _GETSTATSREQUEST._serialized_end=84
  _STAT._serialized_start=86
  _STAT._serialized_end=121
  _GETSTATSRESPONSE._serialized_start=123
  _GETSTATSRESPONSE._serialized_end=184
  _QUERYSTATSREQUEST._serialized_start=186
  _QUERYSTATSREQUEST._serialized_end=271
  _QUERYSTATSRESPONSE._serialized_start=273
  _QUERYSTATSRESPONSE._serialized_end=336
  _SYSSTATSREQUEST._serialized_start=338
  _SYSSTATSREQUEST._serialized_end=355
  _SYSSTATSRESPONSE._serialized_start=358
  _SYSSTATSRESPONSE._serialized_end=552
  _STATSSERVICE._serialized_start=555
  _STATSSERVICE._serialized_end=863
# @@protoc_insertion_point(module_scope)
