# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/headers/tls/config.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='transport/internet/headers/tls/config.proto',
  package='xray.transport.internet.headers.tls',
  syntax='proto3',
  serialized_options=b'\n\'com.xray.transport.internet.headers.tlsP\001Z8github.com/xtls/xray-core/transport/internet/headers/tls\252\002#Xray.Transport.Internet.Headers.Tls',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n+transport/internet/headers/tls/config.proto\x12#xray.transport.internet.headers.tls\"\x0e\n\x0cPacketConfigB\x8b\x01\n\'com.xray.transport.internet.headers.tlsP\x01Z8github.com/xtls/xray-core/transport/internet/headers/tls\xaa\x02#Xray.Transport.Internet.Headers.Tlsb\x06proto3'
)




_PACKETCONFIG = _descriptor.Descriptor(
  name='PacketConfig',
  full_name='xray.transport.internet.headers.tls.PacketConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=98,
)

DESCRIPTOR.message_types_by_name['PacketConfig'] = _PACKETCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PacketConfig = _reflection.GeneratedProtocolMessageType('PacketConfig', (_message.Message,), {
  'DESCRIPTOR' : _PACKETCONFIG,
  '__module__' : 'transport.internet.headers.tls.config_pb2'
  # @@protoc_insertion_point(class_scope:xray.transport.internet.headers.tls.PacketConfig)
  })
_sym_db.RegisterMessage(PacketConfig)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
